# Generated by Django 4.1.7 on 2023-04-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0002_delete_details_delete_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievements_outreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=200000)),
            ],
        ),
        migrations.CreateModel(
            name='awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200000)),
                ('Awarding_agency', models.CharField(blank=True, max_length=200000)),
                ('Year', models.CharField(blank=True, max_length=200000)),
            ],
        ),
        migrations.CreateModel(
            name='book_chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=200000)),
            ],
        ),
        migrations.CreateModel(
            name='conference_papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=200000)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=200000)),
            ],
        ),
        migrations.CreateModel(
            name='current_employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=200000)),
            ],
        ),
        migrations.CreateModel(
            name='international_journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=200000)),
            ],
        ),
        migrations.CreateModel(
            name='patents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=200000)),
            ],
        ),
        migrations.CreateModel(
            name='previous_employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=200000)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=200000)),
                ('Project_investigator', models.CharField(blank=True, max_length=200000)),
                ('Sponsoring', models.CharField(blank=True, max_length=20000)),
                ('Duration', models.CharField(blank=True, max_length=20000)),
                ('Status', models.CharField(blank=True, max_length=200000)),
            ],
        ),
    ]
