# Generated by Django 4.1.7 on 2023-04-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='introductions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BIG_TEXT', models.CharField(blank=True, max_length=200)),
                ('MEDIUM_TEXT', models.CharField(blank=True, max_length=200)),
                ('SMALL_TEXT', models.CharField(blank=True, max_length=200)),
                ('Profile_image', models.ImageField(blank=True, upload_to='images')),
                ('LINK_1', models.CharField(blank=True, max_length=200)),
                ('LINK_1_URL', models.CharField(blank=True, choices=[('index', 'Home Page'), ('mywork', 'My Work Section'), ('aboutme', 'About Me Section'), ('contact', 'Contact Me Section'), ('research', 'Research Group Section'), ('students', 'Students Portal Section'), ('discussion', 'Discussion Section')], max_length=200)),
                ('LINK_2', models.CharField(blank=True, max_length=200)),
                ('LINK_2_URL', models.CharField(blank=True, choices=[('index', 'Home Page'), ('mywork', 'My Work Section'), ('aboutme', 'About Me Section'), ('contact', 'Contact Me Section'), ('research', 'Research Group Section'), ('students', 'Students Portal Section'), ('discussion', 'Discussion Section')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BIG_TEXT', models.CharField(blank=True, max_length=200)),
                ('MEDIUM_TEXT', models.CharField(blank=True, max_length=200)),
                ('SMALL_TEXT', models.CharField(blank=True, max_length=2000)),
                ('IMAGE', models.ImageField(blank=True, upload_to='images/newsletter')),
            ],
        ),
        migrations.CreateModel(
            name='testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(blank=True, max_length=500, verbose_name='testimonial description')),
                ('Name', models.CharField(blank=True, max_length=200, verbose_name='testimonial name')),
                ('Designation', models.CharField(blank=True, max_length=200, verbose_name='testimonial designation')),
                ('Photo', models.ImageField(blank=True, upload_to='images/testimonials', verbose_name='testimonial photo')),
            ],
        ),
    ]
