# Generated by Django 4.1.3 on 2023-04-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='introductions',
            name='Testimonial_section_lower_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='introductions',
            name='Testimonial_section_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
