# Generated by Django 4.1.7 on 2023-04-18 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='research_group_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_class', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='research_group_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=2000)),
                ('Image', models.ImageField(blank=True, upload_to='images/researchgroup')),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchgroup.research_group_class', verbose_name='Name_of_class')),
            ],
        ),
    ]
