# Generated by Django 4.1.3 on 2023-04-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchgroup', '0002_alumni_btech_alumni_ms_alumni_phd_current_btp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_research',
            name='discipline',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
