# Generated by Django 4.1.7 on 2023-04-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=50, verbose_name='testimonial description')),
                ('Name', models.CharField(max_length=120, verbose_name='testimonial name')),
                ('Designation', models.CharField(max_length=120, verbose_name='testimonial designation')),
                ('Photo', models.ImageField(upload_to='', verbose_name='testimonial photo')),
            ],
        ),
    ]
