# Generated by Django 4.1.7 on 2023-04-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BIG_TEXT', models.CharField(max_length=5)),
                ('MEDIUM_TEXT', models.CharField(max_length=10)),
                ('SMALL_TEXT', models.CharField(max_length=20)),
                ('Profile_image', models.ImageField(default='facweb - Copy\textutils\\static\\public\\playground_assets\\puneet gupta-1500w.png', upload_to='images')),
                ('LINK_1', models.CharField(max_length=20)),
                ('LINK_1_URL', models.URLField()),
                ('LINK_2', models.CharField(max_length=20)),
                ('LINK_2_URL', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='Photo',
            field=models.ImageField(default='settings.MEDIA_ROOT/default.png', upload_to='images', verbose_name='testimonial photo'),
        ),
    ]
