# Generated by Django 4.1.7 on 2023-04-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0002_introduction_alter_testimonials_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='BIG_TEXT',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='LINK_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='LINK_2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='MEDIUM_TEXT',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='SMALL_TEXT',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='Description',
            field=models.CharField(max_length=500, verbose_name='testimonial description'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='Designation',
            field=models.CharField(max_length=200, verbose_name='testimonial designation'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='Name',
            field=models.CharField(max_length=200, verbose_name='testimonial name'),
        ),
    ]
