# Generated by Django 4.1.7 on 2023-04-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0004_alter_introduction_link_1_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='LINK_1_URL',
            field=models.CharField(choices=[('index', 'Home Page'), ('mywork', 'My Work Section'), ('aboutme', 'About Me Section'), ('contact', 'Contact Me Section'), ('research', 'Research Group Section'), ('students', 'Students Portal Section'), ('discussion', 'Discussion Section')], max_length=200),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='LINK_2_URL',
            field=models.CharField(choices=[('index', 'Home Page'), ('mywork', 'My Work Section'), ('aboutme', 'About Me Section'), ('contact', 'Contact Me Section'), ('research', 'Research Group Section'), ('students', 'Students Portal Section'), ('discussion', 'Discussion Section')], max_length=200),
        ),
    ]
