# Generated by Django 4.1.7 on 2023-04-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0005_alter_introduction_link_1_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BIG_TEXT', models.CharField(blank=True, max_length=200)),
                ('SMALL_TEXT', models.CharField(blank=True, max_length=200)),
                ('IMAGE', models.ImageField(blank=True, upload_to='images/newsletter')),
            ],
        ),
        migrations.AlterField(
            model_name='introduction',
            name='BIG_TEXT',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='LINK_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='LINK_1_URL',
            field=models.CharField(blank=True, choices=[('index', 'Home Page'), ('mywork', 'My Work Section'), ('aboutme', 'About Me Section'), ('contact', 'Contact Me Section'), ('research', 'Research Group Section'), ('students', 'Students Portal Section'), ('discussion', 'Discussion Section')], max_length=200),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='LINK_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='LINK_2_URL',
            field=models.CharField(blank=True, choices=[('index', 'Home Page'), ('mywork', 'My Work Section'), ('aboutme', 'About Me Section'), ('contact', 'Contact Me Section'), ('research', 'Research Group Section'), ('students', 'Students Portal Section'), ('discussion', 'Discussion Section')], max_length=200),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='MEDIUM_TEXT',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='Profile_image',
            field=models.ImageField(blank=True, default='facweb - Copy\textutils\\static\\public\\playground_assets\\puneet gupta-1500w.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='SMALL_TEXT',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='Description',
            field=models.CharField(blank=True, max_length=500, verbose_name='testimonial description'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='Designation',
            field=models.CharField(blank=True, max_length=200, verbose_name='testimonial designation'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='Name',
            field=models.CharField(blank=True, max_length=200, verbose_name='testimonial name'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='Photo',
            field=models.ImageField(blank=True, default='settings.MEDIA_ROOT/default.png', upload_to='images/testimonials', verbose_name='testimonial photo'),
        ),
    ]
