# Generated by Django 4.1.7 on 2023-04-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0008_socialmediabar_alter_newsletter_small_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediabar',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/socialmedia'),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='Profile_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='Photo',
            field=models.ImageField(blank=True, upload_to='images/testimonials', verbose_name='testimonial photo'),
        ),
    ]
