# Generated by Django 4.1.7 on 2023-04-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0010_contact_alter_socialmediabar_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='FORM_SUBMIT_MESSAGE_TEXT',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
