# Generated by Django 4.1.7 on 2023-04-17 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0012_rename_contact_contacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contacts',
        ),
    ]
