# Generated by Django 4.1.7 on 2023-04-17 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0013_delete_contacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='introduction',
        ),
        migrations.DeleteModel(
            name='newsletter',
        ),
        migrations.DeleteModel(
            name='testimonials',
        ),
    ]
