# Generated by Django 4.1.7 on 2023-04-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0014_delete_introduction_delete_newsletter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SECTION_NAME', models.CharField(blank=True, max_length=2000)),
                ('SECTION_LINK', models.CharField(blank=True, choices=[('index', 'Home Page'), ('mywork', 'My Work Section'), ('aboutme', 'About Me Section'), ('contact', 'Contact Me Section'), ('research', 'Research Group Section'), ('students', 'Students Portal Section'), ('discussion', 'Discussion Section'), ('creators', 'Creators Section')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Navbar_icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICON', models.ImageField(blank=True, upload_to='images/navbar')),
                ('ICON_LINK', models.CharField(blank=True, choices=[('index', 'Home Page'), ('mywork', 'My Work Section'), ('aboutme', 'About Me Section'), ('contact', 'Contact Me Section'), ('research', 'Research Group Section'), ('students', 'Students Portal Section'), ('discussion', 'Discussion Section'), ('creators', 'Creators Section')], max_length=200)),
            ],
        ),
    ]
