# Generated by Django 4.1.3 on 2023-04-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0016_rename_icon_link_socialmediabar_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='socialmediabarmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=2000)),
            ],
        ),
    ]
