# Generated by Django 4.1.7 on 2023-04-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_getintouch_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getintouch_details',
            name='date_time',
        ),
    ]
