# Generated by Django 4.1.7 on 2023-04-21 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_getintouch_details_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getintouch_details',
            name='Message_date',
            field=models.DateField(default=datetime.date(2023, 4, 21)),
        ),
    ]
