# Generated by Django 4.1.7 on 2023-04-21 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_getintouch_details_message_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getintouch_details',
            name='Message_date',
        ),
    ]
