# Generated by Django 4.1.7 on 2023-04-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_remove_getintouch_details_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='getintouch_details',
            name='DateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
