# Generated by Django 4.1.7 on 2023-04-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_getintouch_details_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getintouch_details',
            name='DateTime',
        ),
    ]
