# Generated by Django 4.1.3 on 2023-04-21 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_remove_getintouch_details_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='getintouch_details',
        ),
    ]
