# Generated by Django 4.1.3 on 2023-04-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_delete_getintouch_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='getintouch_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=2000)),
                ('Email', models.EmailField(max_length=2000)),
                ('Subject', models.CharField(default=models.CharField(blank=True, max_length=2000), max_length=10000)),
                ('Message', models.CharField(max_length=10000000)),
            ],
        ),
    ]
